### ISSUE TITLE
Does this plugin still work

### ISSUE THREAD

**Issue by Jibby2121** [LeonBlade/CameraPlugin#1]
Been looking for a camera plugin for ffxiv. To get more of an over the shoulder view on my character when walking or making vids. Not for actual combat. Does this allow that? Also does it work or is there a link to add to the launcher for this plugin?

thanks!

**Comment by LeonBlade** [comment]
You should check out [Cammy](https://github.com/UnknownX7/Cammy), I'm not really maintaining this in any way.
